CREATE TABLE IF NOT EXISTS group_memberships (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL REFERENCES users(id), group_id TEXT NOT NULL REFERENCES groups(id), role TEXT NOT NULL DEFAULT 'member', valid_from INTEGER NOT NULL, valid_to INTEGER NOT NULL, UNIQUE(user_id, group_id));
CREATE TABLE IF NOT EXISTS service_providers (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS services (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES service_providers(id), name TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS service_contracts (id TEXT PRIMARY KEY, service_id TEXT NOT NULL REFERENCES services(id), customer_group_id TEXT NOT NULL REFERENCES groups(id), seat_limit INTEGER, valid_from INTEGER NOT NULL, valid_to INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS group_service_grants (id INTEGER PRIMARY KEY AUTOINCREMENT, group_id TEXT NOT NULL REFERENCES groups(id), service_id TEXT NOT NULL REFERENCES services(id), contract_id TEXT NOT NULL REFERENCES service_contracts(id), seat_limit INTEGER, valid_from INTEGER NOT NULL, valid_to INTEGER NOT NULL, UNIQUE(group_id, service_id));
CREATE TABLE IF NOT EXISTS facilities (id TEXT PRIMARY KEY, structure_no TEXT UNIQUE, building_use TEXT, managing_group_id TEXT NOT NULL REFERENCES groups(id), created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS service_role_master (id INTEGER PRIMARY KEY AUTOINCREMENT, service_id TEXT NOT NULL REFERENCES services(id), facility_type TEXT, role_name TEXT NOT NULL, UNIQUE(service_id, facility_type, role_name));
CREATE TABLE IF NOT EXISTS service_user_assignments (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id TEXT NOT NULL REFERENCES users(id), group_id TEXT NOT NULL REFERENCES groups(id), service_id TEXT NOT NULL REFERENCES services(id), facility_id TEXT NOT NULL REFERENCES facilities(id), service_role_id INTEGER NOT NULL REFERENCES service_role_master(id), valid_from INTEGER NOT NULL, valid_to INTEGER NOT NULL, UNIQUE(user_id, group_id, service_id, facility_id));
CREATE INDEX IF NOT EXISTS idx_membership_user ON group_memberships(user_id);
CREATE INDEX IF NOT EXISTS idx_membership_group ON group_memberships(group_id);
CREATE INDEX IF NOT EXISTS idx_grant_group ON group_service_grants(group_id);
CREATE INDEX IF NOT EXISTS idx_assign_user ON service_user_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_assign_facility ON service_user_assignments(facility_id);
CREATE INDEX IF NOT EXISTS idx_facility_group ON facilities(managing_group_id);
CREATE INDEX IF NOT EXISTS idx_rolemaster_service ON service_role_master(service_id);
CREATE INDEX IF NOT EXISTS idx_groups_parent ON groups(parent_id);
